
--Altarealções do Banco de Dados 28/08/2022

--EXEC sp_rename 'dbo.T_FAMILIA.QTD_MORADORES', 'QTD_MORADORES';

--alter table T_PESSOA add [VL_RENDA] [money] NULL

--alter table T_PESSOA drop column [IDADE]

--alter table T_PESSOA drop column [VALOR_RENDA]

--alter table T_PESSOA add SEXO char(1) NULL

-- Script Final após alterações 

Use  [FICHA_CADASTRAL]
GO
/****** Object:  Table [dbo].[T_ESTADO_CIVIL]    Script Date: 28/08/2022 17:26:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_ESTADO_CIVIL](
	[ID_ESTADO_CIVIL] [int] IDENTITY(1,1) NOT NULL,
	[DC_ESTADO_CIVIL] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ESTADO_CIVIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_FAMILIA]    Script Date: 28/08/2022 17:26:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_FAMILIA](
	[ID_FAMILIA] [int] IDENTITY(1,1) NOT NULL,
	[ID_RESPONSAVEL] [int] NOT NULL,
	[QTD_CRIANCAS] [int] NOT NULL DEFAULT 0,
	[QTD_EMPREGADOS] [int] NOT NULL DEFAULT 0,
	[END_CEP_FAMILIA] [varchar](8) NULL,
	[END_DC_FAMILIA] [varchar](150) NULL,
	[END_NUMERO] [varchar](10) NULL,
	[END_BAIRRO_FAMILIA] [varchar](100) NULL,
	[END_MUNICIPIO] [varchar](20) NULL,
	[END_PONTO_REF] [varchar](200) NULL,
	[END_COMPLEMENTO_FAMILIA] [varchar](100) NULL,
	[FL_RESIDENCIA_PROPRIA] [bit] NOT NULL DEFAULT 0,
	[FL_CESTA_BASICA] [bit] NOT NULL DEFAULT 0,
	[RELATO_VIDA] [varchar](500) NULL,
	[VL_RENDA] [money] NOT NULL DEFAULT 0,
	[QTD_MORADORES] [int] NOT NULL DEFAULT 0,
PRIMARY KEY CLUSTERED 
(
	[ID_FAMILIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_PAROQUIA]    Script Date: 28/08/2022 17:26:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_PAROQUIA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DC_PAROQUIA] [varchar](50) NOT NULL,
	[END_DC_PAROQUIA] [varchar](150) NULL,
	[END_BAIRRO_PAROQUIA] [varchar](100) NULL,
	[PAROCO] [varchar](50) NULL,
	[END_CEP] [varchar](8) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_PESSOA]    Script Date: 28/08/2022 17:26:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_PESSOA](
	[ID_PESSOA] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](100) NOT NULL,
	[DT_NASC] [datetime] NULL,
	[CPF] [varchar](14) NULL,
	[RG] [varchar](20) NULL,
	[CELULAR] [varchar](16) NULL,
	[TELEFONE] [varchar](16) NULL,
	[ST_BATISMO] [bit] NOT NULL DEFAULT 0,
	[ST_CRISMA] [bit] NOT NULL DEFAULT 0,
	[ST_EUCARISTIA] [bit] NOT NULL DEFAULT 0,
	[ST_MATRIMONIO] [bit] NOT NULL DEFAULT 0,
	[ID_ESTADO_CIVIL] [int] NULL,
	[PROFISSAO] [varchar](50) NULL,
	[ID_ST_EMPREGO] [int] NULL,
	[ID_FAMILIA] [int] NULL,
	[SEXO] [char](1) NULL,
PRIMARY KEY CLUSTERED
(
	[ID_PESSOA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_ST_EMPREGO]    Script Date: 28/08/2022 17:26:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_ST_EMPREGO](
	[ID_ST_EMPREGO] [int] IDENTITY(1,1) NOT NULL,
	[DC_ST_EMPREGO] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ST_EMPREGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_FAMILIA]  WITH CHECK ADD constraint FK_RESP_FAMILIA FOREIGN KEY ([ID_RESPONSAVEL])
REFERENCES [dbo].[T_PESSOA] ([ID_PESSOA])
GO
ALTER TABLE [dbo].[T_PESSOA]  WITH CHECK ADD constraint FK_ESTADO_CIVIL_PESSOA FOREIGN KEY([ID_ESTADO_CIVIL])
REFERENCES [dbo].[T_ESTADO_CIVIL] ([ID_ESTADO_CIVIL])
GO
ALTER TABLE [dbo].[T_PESSOA]  WITH CHECK ADD constraint FK_FAMILIA_PESSOA FOREIGN KEY([ID_FAMILIA])
REFERENCES [dbo].[T_FAMILIA] ([ID_FAMILIA])
GO
ALTER TABLE [dbo].[T_PESSOA]  WITH CHECK ADD constraint FK_ST_EMPREGO_PESSOA FOREIGN KEY([ID_ST_EMPREGO])
REFERENCES [dbo].[T_ST_EMPREGO] ([ID_ST_EMPREGO])
GO


